#!/bin/sh
sudo apt-get update
sudo apt-get upgrade

sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    byobu

sudo apt-get install -y docker.io
sudo apt-get install ffmpeg libavcodec-extra
sudo apt install python3-autopep8